int i_ = 0;
int pptr_first_good_ = 1;
int lastfilt_ = 16;
int m1_ = 0;
int histo_length_ = 100;
int length_ = 0;
int k_ = 0;
int stat_lt_[100][30];
int i_call_ = 20;
int histo_step_framesize_ = 10;
float average_ = 0;
int j_ = 0;
int mmax_lp_ = 0;
int mindex_ = 0;
float hptr_noiseOLD_[100];
